name = "Spice"
uuid = "73935808-6ee9-471b-bbc5-d53102a46a1f"
authors = ["Ntigura Yann"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
